#!/bin/bash -e

# git-combine-with-work
#   by Steven Elliott <selliott512@gmail.com>
#
# This is like git-combine-with-previous except that a commit of modified
# files is created first.  Note that untracted files must be added if
# they are to be included.
#
# Examples:
#   Add changes in the working directory to the latest commit (HEAD):
#     git-combine-with-work

git commit -am 'This commit will be combined with the previous one.'
git-combine-with-previous "$@"
