#!/bin/bash

# git-current-branch
#   by Steven Elliott <selliott512@gmail.com>
#
# Write the current branch to stdout.
#
# Examples:
#   Write the current branch to stdout.
#     git-current-branch

git rev-parse --abbrev-ref HEAD
