#!/bin/bash -e

# git-combine-with-previous ver 0.9.0
#   by Steven Elliott <selliott512@gmail.com>
#
# Combine second to last commit (HEAD~) with the last commit (HEAD) and use
# the commit message from the second to last (HEAD~) commit.  This helpful
# when a local commit needs to be amended.  The additional work can be given
# a short commit message that will only be used locally (or just "temp" or
# whatever).  The commits can then be combined later once the new commit has
# been sufficiently considered.
#
# Examples:
#   Set the two most recent commits:
#     git-combine-with-previous

git reset --soft HEAD~2
git cm -C ORIG_HEAD~
