#!/usr/bin/env python

# git-deflate-object ver 0.9.0
#   by Steven Elliott <selliott512@gmail.com>
#
# Applies the deflate algorithm to a git object and writes the result to.
# stdout.  It can be used to see the exact contents of the git object.  It's
# similar to 
#   git show --pretty=raw <object>
# except that the object header ("blob", etc.) is included.  Note that this
# tool only works if the object exists as an ordinary file in .git/objects
# (as opposed to in a pack file or alternate).  This tool only works in the
# top level directory.
#
# Examples:
#   Deflate and write the contents of a git object to stdout:
#     git-deflate-object b69549239a15fc9e07c8e85074f2b084f2adf995

import os
import sys
import zlib

# TODO: It should walk up the path to find the .git dir.
bname = os.path.basename(sys.argv[0])
if len(sys.argv) != 2:
    print >> sys.stderr, "Usage:", bname, "hash"
    sys.exit(1)
hname = sys.argv[1]
hpath = ".git/objects/" + hname[:2] + "/" + hname[2:]

try:
    hhand = open(hpath)
except IOError, err:
    print >> sys.stderr, "Could not open %s for read: %s" % (hpath, err)
    sys.exit(1)

hstr = hhand.read()    
sys.stdout.write(zlib.decompress(hstr))
